### PR TITLE
Use cork() in streamFile

### PR DESCRIPTION
**Pull request by charleprr**
In recent versions of µWebSockets, there is now a warning telling you to cork() responses before writing to them for better performance. This does exactly that, and removes the warning.

```Warning: uWS.HttpResponse writes must be made from within a corked callback. See documentation for uWS.HttpResponse.cork and consult the user manual.```

More info in the user manual: https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md#corking

### CODE REVIEW

**Comment by snkj5** [comment]
thanks for your contribution! the code looks fine, I'm going to merge it

**Comment by snkj5** [comment]
your changes are included in the v1.0.8 version

**Comment by charleprr** [comment]
Thank you!

**Comment by charleprr** [comment]
I can see my change in the `src/index.ts`, but not in the `dist/index.js` file, and I still get the warning.
The package hasn't been rebuilt in the v1.0.8 version.

**Pull request merged**
